// =========================================================
// Mock "my activity" (no backend yet). Three streams shown in the
// community hub under "Activitatea mea":
//   - received: replies/comments others left on my posts or comments
//   - given:    comments I left on other people's posts
//   - followed: posts I chose to follow (pinned) — derived live from the
//               forum feed so toggling "urmărește" updates it instantly.
// Content is Romanian; identifiers stay English.
// =========================================================
import { userById, initials, avatarColor } from "./community-data.js";
import { relTime } from "./forum-data.js";

const MIN = 60 * 1000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

function person(id) {
  const u = userById(id) || { name: "Membru" };
  return { authorId: id, name: u.name, initials: initials(u.name), color: avatarColor(id) };
}

// "Seen" state survives reloads — otherwise the badge kept resurrecting
// after every full page load even though everything had been read.
const READ_KEY = "atelier_activity_read";
const seedsRead = typeof localStorage !== "undefined" && localStorage.getItem(READ_KEY) === "1";

// `postMatch` is a distinctive fragment of the source post's text — the hub
// resolves it to the live post so the row can link to where it happened.
// (Live entries carry a direct postId instead; `goSection` links a row to a
// hub section when there's no single post behind it, e.g. friend requests.)
function entry({ actorId, agoMs, kind, action, snippet, context, postMatch = null, postId = null, goSection = null, read = seedsRead }) {
  return { ...person(actorId), time: relTime(agoMs), kind, action, snippet, context, postMatch, postId, goSection, read };
}

// Activity kinds → icon + accent, so each row reads at a glance.
// (SVGs are 24×24, currentColor; the UI tints them per kind.)
export const ACTIVITY_KINDS = {
  comment: {
    label: "Comentariu",
    color: "#2563eb",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.4 8.4 0 0 1-8.5 8.5 9 9 0 0 1-4-.9L3 20l1.4-4.2A8.4 8.4 0 0 1 12.5 3 8.4 8.4 0 0 1 21 11.5z"/></svg>`,
  },
  like: {
    label: "Apreciere",
    color: "#db2777",
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 21s-7-4.35-9.5-8.5C1 9.5 2.5 6 6 6c2 0 3.2 1.2 4 2.3C10.8 7.2 12 6 14 6c3.5 0 5 3.5 3.5 6.5C19 16.65 12 21 12 21z"/></svg>`,
  },
  reply: {
    label: "Răspuns",
    color: "#16a34a",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 17l-5-5 5-5"/><path d="M4 12h11a5 5 0 0 1 5 5v2"/></svg>`,
  },
  poke: {
    label: "Poke",
    color: "#f59e0b",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12h14"/><path d="M10 6l6 6-6 6"/><circle cx="20" cy="12" r="2"/></svg>`,
  },
  award: {
    label: "Recompensă",
    color: "#16a34a",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="9" r="6"/><path d="M9 14l-1.5 7L12 18l4.5 3L15 14"/></svg>`,
  },
  friend: {
    label: "Prietenie",
    color: "#7c3aed",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0"/><path d="M18 8v6M21 11h-6"/></svg>`,
  },
  mention: {
    label: "Mențiune",
    color: "#0891b2",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M16 12v1.5a2.5 2.5 0 0 0 5 0V12a9 9 0 1 0-3.5 7.1"/></svg>`,
  },
};

// Replies/likes I received on my content — PLUS live entries generated by
// real events (correct-mark, approvals, mentions, friend requests).
export const ACTIVITY_RECEIVED = [
  entry({ actorId: 7, agoMs: 3 * HOUR, kind: "friend", action: "vrea să-ți fie prieten(ă)", snippet: "Acceptă sau refuză cererea din profilul tău.", context: "Cerere de prietenie", goSection: "profil" }),
  entry({ actorId: 11, agoMs: 9 * HOUR, kind: "friend", action: "vrea să-ți fie prieten(ă)", snippet: "Acceptă sau refuză cererea din profilul tău.", context: "Cerere de prietenie", goSection: "profil" }),
  entry({ actorId: 1, agoMs: 2 * HOUR, kind: "comment", action: "a comentat la postarea ta", snippet: "Felicitări! Urmează timpurile compuse…", context: "Reușită · «Am terminat lecția despre verb»", postMatch: "Am terminat lecția despre verb" }),
  entry({ actorId: 4, agoMs: 6 * HOUR, kind: "like", action: "a apreciat comentariul tău", snippet: "„î” la început și sfârșit, „â” în interior.", context: "Discuție publică", postMatch: "Mic truc" }),
  entry({ actorId: 12, agoMs: 1 * DAY, kind: "reply", action: "ți-a răspuns", snippet: "Și eu mă pregătesc pentru Drept, hai să exersăm!", context: "Întrebare · «Caut pe cineva…»", postMatch: "Caut pe cineva cu care să exersez" }),
];

// Comments I gave elsewhere.
export const ACTIVITY_GIVEN = [
  entry({ actorId: 0, agoMs: 40 * MIN, kind: "comment", action: "ai comentat la postarea lui Maria Ionescu", snippet: "Direct = „pe cine? ce?”, indirect = „cui?”.", context: "Întrebare · complement direct/indirect", postMatch: "complementul direct de cel indirect", read: true }),
  entry({ actorId: 0, agoMs: 5 * HOUR, kind: "reply", action: "ai răspuns lui Vlad Georgescu", snippet: "Bravo pentru streak, mă motivezi!", context: "Reușită · streak 22 de zile", postMatch: "Streak de 22 de zile", read: true }),
];

// ---------------------------------------------------------
// Live helpers — the notifications badge counts only UNREAD received
// items and clears when the user visits "Activitatea mea"; commenting on
// someone else's post appends a real "given" entry.
// ---------------------------------------------------------

/** Unread received notifications (drives the badge). */
export function unreadActivityCount() {
  return ACTIVITY_RECEIVED.filter((a) => !a.read).length;
}

/** Mark everything received as read (called when the tab is opened) and
 *  remember it across reloads. */
export function markActivityRead() {
  for (const a of ACTIVITY_RECEIVED) a.read = true;
  try {
    localStorage.setItem(READ_KEY, "1");
  } catch {
    /* private mode — fine, in-memory flags still work */
  }
}

/** Record a comment/reply I just gave on someone else's content. */
export function recordGiven({ kind, action, snippet, context, postId = null }) {
  ACTIVITY_GIVEN.unshift(entry({ actorId: 0, agoMs: 0, kind, action, snippet, context, postId, read: true }));
}

/** A REAL event just landed in MY inbox (correct-mark, approval, mention…).
 *  Shows up unread in the bell + „Activitatea mea”. */
export function notifyReceived({ actorId, kind, action, snippet, context, postId = null, goSection = null }) {
  ACTIVITY_RECEIVED.unshift(entry({ actorId, agoMs: 0, kind, action, snippet, context, postId, goSection, read: false }));
}

/** Notify ANOTHER member (e.g. an @mention). In the mock only the current
 *  user's inbox exists, so other targets are a no-op — with Supabase this
 *  becomes an insert into the target's notifications. */
export function notifyUser(targetId, payload) {
  if (targetId === 0) notifyReceived(payload);
}
